//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.IO;
using System.IO.Compression;
class Compressor
{
		public static byte[] compress (byte[] buffer)
		{
				MemoryStream ms = new MemoryStream ();
				GZipStream zip = new GZipStream (ms, CompressionMode.Compress, true);
				zip.Write (buffer, 0, buffer.Length);
				zip.Close ();
				ms.Position = 0;
		
				byte[] compressed = new byte[ms.Length];
				ms.Read (compressed, 0, compressed.Length);
		
				byte[] gzBuffer = new byte[compressed.Length + 4];
				Buffer.BlockCopy (compressed, 0, gzBuffer, 4, compressed.Length);
				Buffer.BlockCopy (BitConverter.GetBytes (buffer.Length), 0, gzBuffer, 0, 4);
				return gzBuffer;
		}
		public static byte[] decompress (byte[] gzBuffer)
		{
				MemoryStream ms = new MemoryStream ();
				int msgLength = BitConverter.ToInt32 (gzBuffer, 0);
				ms.Write (gzBuffer, 4, gzBuffer.Length - 4);
		
				byte[] buffer = new byte[msgLength];
		
				ms.Position = 0;
				GZipStream zip = new GZipStream (ms, CompressionMode.Decompress);
				zip.Read (buffer, 0, buffer.Length);
		
				return buffer;
		}
}

