//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using SimpleSQL;


/**
* Holds any persisted data that Rendering Chunks need to build the environment
**/
public class ChunkData
{
//		public int positionX { get; set; }
//		public int positionY { get; set; }
//		public int positionZ { get; set; }
//
//		public int[,,] voxels { get; set; }

		public int x { get; set; }

		public int y { get; set; }

		public int z { get; set; }
	
		public int[,,] blocks { get; set; }
		
		public class ChunkDataDO
		{
				[PrimaryKey]
				public int x { get; set; }
				[PrimaryKey]
				public int y { get; set; }
				[PrimaryKey]
				public int z { get; set; }
		
				[NotNull]
				public string blocks { get; set; }
		}
		
		
		
		public ChunkData ()
		{

			
		}
		
}