//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;

public class ItemChunk
{
		private LinkedList<Vector3> items;
		//public Region region;
		public bool update = false;
		
		public ItemChunk ()
		{
				items = new LinkedList<Vector3> ();
		
		}
		
		public void addItem (Vector3 newItem)
		{
				items.AddLast (newItem);
				update = true;
		}
		
//		public void renderItems (Chunk parent, Region region, GameObject treeMesh)
//		{
//				foreach (Vector3 position in items) {
//						GameObject newItem = GameObject.Instantiate (treeMesh,
//			                                  new Vector3 (position.x + region.getBlockOffsetX (), 
//			                                  position.y, position.z + region.getBlockOffsetZ ()),
//			                                  new Quaternion (0, 180, 0, 0)) as GameObject;
//						newItem.transform.parent = parent.transform;
//				}
//		}
}


