//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class Item
{
		public int blockX, blockY, blockZ;
		public int offsetX, offsetY, offsetZ;
		//public GameObject itemMesh;

		public void generateMesh (Chunk chunk)
		{
//				GameObject newItem = Instantiate (itemMesh,
//		                                  new Vector3 (blockX + offsetX, blockY + offsetY, blockZ + offsetZ),
//		                                   new Quaternion (0, 0, 0, 0)) as GameObject;
//				newItem.transform.parent = chunk.transform;
		}
}

