//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class TerrainWalker
{
		public VoxelWorld world;
		public int blockX, blockY, blockZ;		//These are world coords.

		public TerrainWalker (VoxelWorld inWorld)
		{
				world = inWorld;
		}

		public void gotoPosition (int x, int z)
		{
				//Get the region.
				blockX = x;
				blockZ = z;
				//Determine what height the point is
				Region region = world.getRegionAtCoords (x, z);
				int[] localCoords = region.convertWorldToLocal (x, 0, z);
				for (int y = region.regionY - 1; y >= 0; y--) {
						if (region.GetBlockAtCoords (localCoords [0], y, localCoords [2]) != 0) {
								blockY = y + 1;
								break;
						}

				}
		}
	
}

