//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Threading;
using System.Collections;
using System.Collections.Generic;

public class VoxelWorld : MonoBehaviour
{
		public GameObject regionPrefab;
		public int regionXZ = 32;
		public int regionY = 32;
		private Dictionary<string, Region> regions;
		private LinkedList<Region> dirtyRegions;
		private VoxelModifyTerrain clientRenderer;
		public bool useDisk = false;
		
		void Start ()
		{
		
				//Start singleton managers
				WorldGeneration instance = WorldGeneration.Instance;
				
				Region.setWorld (this);
				regions = new Dictionary<string, Region> ();
				Region centerRegion = createRegion (0, 0, 0, false);
				loadAllNeighbors (centerRegion, false);
				
				//Initialize Chunk Manager
				GameObject chunkManagerGO = GameObject.Find ("Chunk Manager") as GameObject;
				ChunkManager manager = chunkManagerGO.GetComponent<ChunkManager> ();
				manager.createChunkPool ();

				clientRenderer = gameObject.GetComponent ("VoxelModifyTerrain") as VoxelModifyTerrain;
				clientRenderer.setStartRegion (centerRegion);


				InvokeRepeating ("SaveToDiskEvent", 30f, 30f);
		}

		public void changeFocusRegion (Region newRegion)
		{
				//Load up region neighbors. Create a new regions as needed.
				loadAllNeighbors (newRegion, true);  


		}

		/**
	 * Gets the region at the specified indices in the Dictionary
	 * 
	 **/
		public Region getRegionAtIndex (int x, int y, int z)
		{
				string key = x + "x" + y + "x" + z;
				if (regions.ContainsKey (key)) {
						return regions [key];
				} else {
						
						Region region = createRegion (x, y, z, false);
						//loadAllNeighbors (region, true);  
						return region;
				}
		
		}
	
		/**
	 * Gets the region containing the specified world cordinates
	 * 
	 **/
		public Region getRegionAtCoords (int x, int y, int z)
		{
				if (x < 0) {
						x = x - regionXZ + 1;
				}
				if (z < 0) {
						z = z - regionXZ + 1;
				}
				//y will never be less than zero
			
				int regionsX = x / regionXZ;
				int regionsY = y / regionY;
				int regionsZ = z / regionXZ;


				return getRegionAtIndex (regionsX, regionsY, regionsZ);
	
		}
		
		private void loadAllNeighbors (Region region, bool isAsync)
		{

				//North
				Region neighbor = getRegionAtIndex (region.offsetX, region.offsetY, region.offsetZ + 1);
				if (neighbor == null) {
						neighbor = createRegion (region.offsetX, region.offsetY, region.offsetZ + 1, isAsync);
				}


				//South
				neighbor = getRegionAtIndex (region.offsetX, region.offsetY, region.offsetZ - 1);
				if (neighbor == null) {
						neighbor = createRegion (region.offsetX, region.offsetY, region.offsetZ - 1, isAsync);
				}

				//East
				neighbor = getRegionAtIndex (region.offsetX + 1, region.offsetY, region.offsetZ);
				if (neighbor == null) {
						neighbor = createRegion (region.offsetX + 1, region.offsetY, region.offsetZ, isAsync);
				}

				//West
				neighbor = getRegionAtIndex (region.offsetX - 1, region.offsetY, region.offsetZ);
				if (neighbor == null) {
						neighbor = createRegion (region.offsetX - 1, region.offsetY, region.offsetZ, isAsync);
				}

				//NorthWest
				neighbor = getRegionAtIndex (region.offsetX - 1, region.offsetY, region.offsetZ + 1);
				if (neighbor == null) {
						neighbor = createRegion (region.offsetX - 1, region.offsetY, region.offsetZ + 1, isAsync);
				}

				//SouthEast
				neighbor = getRegionAtIndex (region.offsetX + 1, region.offsetY, region.offsetZ - 1);
				if (neighbor == null) {
						neighbor = createRegion (region.offsetX + 1, region.offsetY, region.offsetZ - 1, isAsync);
				}

				//NorthEast
				neighbor = getRegionAtIndex (region.offsetX + 1, region.offsetY, region.offsetZ + 1);
				if (neighbor == null) {
						neighbor = createRegion (region.offsetX + 1, region.offsetY, region.offsetZ + 1, isAsync);
				}

				//SouthWest
				neighbor = getRegionAtIndex (region.offsetX - 1, region.offsetY, region.offsetZ - 1);
				if (neighbor == null) {
						neighbor = createRegion (region.offsetX - 1, region.offsetY, region.offsetZ - 1, isAsync);
				}

		}

		public void saveWorld ()
		{
				foreach (KeyValuePair<string,Region> kvp in regions) {
						kvp.Value.saveRegion ();
				}
		}

		private Region createRegion (int x, int y, int z, bool isAsync)
		{

				Region region = new Region ();
				//GameObject regionGO = regionPool.First.Value;
				//regionPool.RemoveFirst ();
				//Region region = regionGO.GetComponent ("Region") as Region;
				region.regionXZ = this.regionXZ;
				region.regionY = this.regionY;
				region.regionXZ = this.regionXZ;
				region.offsetX = x;
				region.offsetY = y;
				region.offsetZ = z;
				//Debug.Log ("Adding region " + region.hashString ());
				regions.Add (region.hashString (), region);
				if (isAsync) {
						Thread oThread = new Thread (new ThreadStart (region.create));
						oThread.Start ();
				} else {
						region.create ();
				}
				
				
				return region;
		}

		private void SaveToDiskEvent ()
		{
				if (useDisk) {
						foreach (KeyValuePair<string,Region> kvp in regions) {
								//TODO: Possible ConcurrentModification here.
								if (kvp.Value.isDirty) {
										Thread oThread = new Thread (new ThreadStart (kvp.Value.saveRegion));
										oThread.Start ();
								}
						}
				}
			
		}

}