//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class WorldGeneration
{
		private static volatile WorldGeneration instance;
	
	
		private WorldGeneration ()
		{

		}
		public static WorldGeneration Instance {
				get {
						if (instance == null) 
								instance = new WorldGeneration ();
						return instance;
				}
		}
		
		
		public void createPerlin (byte[,,] data, int regionX, int regionZ)
		{
				for (int x=0; x<data.GetLength(0); x++) {
						for (int z=0; z<data.GetLength(2); z++) {
								int stone = PerlinNoise (regionX + x, 0, regionZ + z, 100, 20, 1.2f);
								stone += PerlinNoise (regionX + x, 700, regionZ + z, 20, 4, 0) + 10;
								int dirt = PerlinNoise (regionX + x, 100, regionZ + z, 50, 2, 0);
				
								for (int y=0; y<data.GetLength(1); y++) {
										if (y <= stone) {
												data [x, y, z] = 1;
										} else if (y <= dirt + stone) { 
												data [x, y, z] = 2;
										}
					
								}
						}
				}
		}
		
		public void createFlatBiome (byte[,,] data)
		{
				for (int x=0; x<data.GetLength(0); x++) {
						for (int z=0; z<data.GetLength(2); z++) {
								for (int y=0; y<data.GetLength(1); y++) {
										if (y <= (data.GetLength (1) / 2)) {
												data [x, y, z] = 1;
										}
								}
						}
				}	
		}
		
		private int PerlinNoise (float x, int y, float z, float scale, float height, float power)
		{
				float rValue;
				rValue = Noise.GetNoise (((double)x) / scale, ((double)y) / scale, ((double)z) / scale);
				rValue *= height;
		
				if (power != 0) {
						rValue = Mathf.Pow (rValue, power);
				}
		
				return (int)rValue;
		}
	
}

