//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class WorldGeneration
{
		private static volatile WorldGeneration instance;
	
		
	
		private WorldGeneration ()
		{

		}
		public static WorldGeneration Instance {
				get {
						if (instance == null) 
								instance = new WorldGeneration ();
						return instance;
				}
		}
		
		
		public void createPerlin (byte[,,] data, int regionX, int regionY, int regionZ)
		{
				for (int x=0; x<data.GetLength(0); x++) {
						for (int z=0; z<data.GetLength(2); z++) {
								int xi = regionX + x;
								int zi = regionZ + z;
						
								int stone = PerlinNoise (xi, 0, zi, 100, 2, 1.2f) + PerlinNoise (xi, 0, zi, 200, 10, 2.3f) + 10;
								int dirt = PerlinNoise (xi, 0, zi, 500, 5, 1.3f);
				
								for (int y=0; y<data.GetLength(1); y++) {
										if (y <= stone) {
												data [x, y, z] = 1;
										} else if (y <= dirt + stone) { 
												data [x, y, z] = 2;
										}
					
								}
						}
				}
		}
		
		public void createFlatBiome (byte[,,] data)
		{
				for (int x=0; x<data.GetLength(0); x++) {
						for (int z=0; z<data.GetLength(2); z++) {
								for (int y=0; y<data.GetLength(1); y++) {
										if (y <= (data.GetLength (1) / 2)) {
												data [x, y, z] = 1;
										}
								}
						}
				}	
		}
		
		private int PerlinNoise (float x, int y, float z, float scale, float height, float power)
		{
				float rValue;
				rValue = Noise.GetNoise (((double)x) / scale, ((double)y) / scale, ((double)z) / scale);
				rValue *= height;
		
				if (power != 0) {
						rValue = Mathf.Pow (rValue, power);
				}
		
				return (int)rValue;
		}
	
}

