//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class TerrainWalker
{
		public VoxelWorld world;
		public int blockX, blockY, blockZ;		//These are world coords.

		public TerrainWalker ()
		{

		}

		public  int dropFromSky (int x, int z, int startingHeight)
		{
				//TODO:  Fix this method to work with 3d regions.
//				//Get the region.
				blockX = x;
				blockZ = z;
				//Drop the walker from the given starting height.
				for (int y = startingHeight; y > WorldGeneration.seaLevel; y--) {
						Region region = world.getRegionAtCoords (x, y, z);
						int[] localCoords = region.convertWorldToLocal (x, y, z);
						for (int yi = Region.regionY - 1; yi >= 0; yi--) {
								if (region.GetBlockAtRelativeCoords (localCoords [0], yi, localCoords [2]) != 0) {
										return blockY = yi + 1;
								}

						}
				}
				return 0;  //return bedrock bottom :/
		}
		
}

